package com.yuno.commons.mdc;

/**
 * Centralised MDC key constants.
 *
 * Every service and Kafka consumer uses these keys so log aggregation tools
 * (ELK, Datadog, Grafana Loki) can correlate log lines across the entire
 * transaction lifecycle with a single query like:
 *
 *   transactionId:"abc-123" → shows ALL logs from payment-service,
 *   provider-service, idempotency-service, notification-service
 *   for that specific payment.
 *
 * Kafka header names mirror MDC key names (used by MDCUtil for propagation).
 */
public final class MDCKeys {

    private MDCKeys() {}

    /** UUID of the payment — set once in payment-service, propagated everywhere. */
    public static final String TRANSACTION_ID  = "transactionId";

    /** UUID generated by api-gateway per HTTP request — ties HTTP + Kafka hops. */
    public static final String CORRELATION_ID  = "correlationId";

    /** User/merchant ID from X-User-Id request header. */
    public static final String USER_ID         = "userId";

    /** Name of the current microservice (set once in each app's MDCFilter). */
    public static final String SERVICE_NAME    = "serviceName";

    /** HTTP header names (used by gateway and services) */
    public static final String HEADER_CORRELATION_ID = "X-Correlation-Id";
    public static final String HEADER_USER_ID         = "X-User-Id";
    public static final String HEADER_IDEMPOTENCY_KEY = "Idempotency-Key";

    /** Kafka record header names (mirrors MDC keys for easy propagation). */
    public static final String KAFKA_HEADER_TRANSACTION_ID = "mdc-transactionId";
    public static final String KAFKA_HEADER_CORRELATION_ID = "mdc-correlationId";
    public static final String KAFKA_HEADER_USER_ID        = "mdc-userId";
}
