server:
  port: 8083

spring:
  application:
    name: idempotency-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/yuno_idempotency_db
    username: ${DB_USER:yuno}
    password: ${DB_PASS:yuno_secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      pool-name: IdempotencyHikariPool

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 1000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yuno.idempotency.model
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 10

logging:
  level:
    com.yuno.idempotency: INFO
    org.mybatis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [trxId=%X{transactionId:-}] [corrId=%X{correlationId:-}] [svc=%X{serviceName:-}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/idempotency-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:idempotency_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
